### ISSUE TITLE
Make username available to caller

### ISSUE THREAD

**Issue by dcoshea** [stregone/mojolicious-plugin-basicauthplus#4]
It would be useful if, in case of successful authentication, the username was made available to the calling code.

For example, `basic_auth()` could return the username instead of `1`, but perhaps a hash should be returned in case other values need to be returned in the future?

**Comment by stregone** [comment]
I can see the value in this, and returning the username should be no problem.  Returning a hash is intriguing, but I would like to do it in such a way that it doesn't break things for users who are expecting a simple integer return value.  I'll think it over.  Thanks for your suggestion.

**Comment by stregone** [comment]
I think the answer is for basic_auth() to return two values, the first of which would still be 1 or 0 for success/failure, and the second would be a hash ref.  The hash would always contain the username, and, as you say, could contain other values in the future.

**Comment by stregone** [comment]
Or rather the first element returned would be the hash ref, whereas the second value would be 1 or 0, in order to keep simple list assignment to a scalar variable working for users who depend on it.

**Comment by stregone** [comment]
Just pushed new version with this feature.
